name: Build, Test and Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy_to_staging:
  test_staging:
    needs: deploy_to_staging
  deploy_to_production:
    needs: [deploy_to_staging, test_staging]
